import type { LucideIcon } from 'lucide-react'
import {
  LayoutDashboard,
  FileText,
  BarChart3,
  Settings,
  CreditCard,
  Users,
  Bell,
  Heart,
  Home,
  Search,
  Mail,
  BookOpen,
  HelpCircle,
  Folder,
  Tag,
  Image,
  Link,
  MessageCircle,
  Star,
  Shield,
  Rocket,
  Zap,
  Palette,
  Clipboard,
  Music,
  Video,
  Files,
  Lock,
  Key,
  PieChart,
} from 'lucide-react'

export const iconMap: Record<string, LucideIcon> = {
  'layout-dashboard': LayoutDashboard,
  'file-text': FileText,
  'bar-chart-3': BarChart3,
  'settings': Settings,
  'credit-card': CreditCard,
  'users': Users,
  'bell': Bell,
  'heart': Heart,
  'home': Home,
  'search': Search,
  'mail': Mail,
  'book-open': BookOpen,
  'help-circle': HelpCircle,
  'folder': Folder,
  'tag': Tag,
  'image': Image,
  'link': Link,
  'message-circle': MessageCircle,
  'star': Star,
  'shield': Shield,
  'rocket': Rocket,
  'zap': Zap,
  'palette': Palette,
  'clipboard': Clipboard,
  'music': Music,
  'video': Video,
  'files': Files,
  'lock': Lock,
  'key': Key,
  'pie-chart': PieChart,
}

export function getIcon(name: string | null | undefined): LucideIcon {
  if (!name) return FileText
  return iconMap[name] || FileText
}
